# Add site configurations to `sites` array
# @NOTE You don't need to restart the container when editing this file.

# Check RNZ's featured article once per hour
[[sites]]
url = 'https://www.rnz.co.nz'
selector = '.lead-story.lead-story--standard'
frequency = '1hour'

# Monitor The Co-operative Bank's website for new deployments
[[sites]]
url = 'https://www.co-operativebank.co.nz/?displayVersions=1'
selector = '.footer .wrapper > div:last-child'
frequency = '1day'
